"""Generate the two reviewable CloudFormation templates. No AWS mutations."""
import json
from pathlib import Path
P=Path(__file__).parent
ref=lambda x:{'Ref':x}
get=lambda x,a:{'Fn::GetAtt':[x,a]}
sub=lambda x:{'Fn::Sub':x}
def resource(t,p,**kw): return {'Type':'AWS::'+t,'Properties':p,**kw}
def role(service, statements):
 return resource('IAM::Role',{'AssumeRolePolicyDocument':{'Version':'2012-10-17','Statement':[{'Effect':'Allow','Principal':{'Service':service},'Action':'sts:AssumeRole'}]},'Policies':[{'PolicyName':'scoped','PolicyDocument':{'Version':'2012-10-17','Statement':statements}}]})
def allow(actions, resources, **kw): return dict(Effect='Allow',Action=actions,Resource=resources,**kw)
def bucket(): return resource('S3::Bucket',{'PublicAccessBlockConfiguration':{'BlockPublicAcls':True,'BlockPublicPolicy':True,'IgnorePublicAcls':True,'RestrictPublicBuckets':True},'BucketEncryption':{'ServerSideEncryptionConfiguration':[{'ServerSideEncryptionByDefault':{'SSEAlgorithm':'AES256'}}]},'LifecycleConfiguration':{'Rules':[{'Id':'expire','Status':'Enabled','ExpirationInDays':7,'AbortIncompleteMultipartUpload':{'DaysAfterInitiation':1}}]}},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
r={}
r['SourceBucket']=bucket()
r['Repository']=resource('ECR::Repository',{'RepositoryName':'hishin-prod','ImageScanningConfiguration':{'ScanOnPush':True},'ImageTagMutability':'IMMUTABLE','LifecyclePolicy':{'LifecyclePolicyText':json.dumps({'rules':[{'rulePriority':1,'selection':{'tagStatus':'any','countType':'imageCountMoreThan','countNumber':5},'action':{'type':'expire'}}]})}},DeletionPolicy='Retain')
r['BuildLogs']=resource('Logs::LogGroup',{'LogGroupName':'/hishin/prod/build','RetentionInDays':7})
r['BuildRole']=role('codebuild.amazonaws.com',[
 allow(['logs:CreateLogStream','logs:PutLogEvents'],sub('${BuildLogs.Arn}')),
 allow(['s3:GetObject'],sub('${SourceBucket.Arn}/*')),
 allow(['s3:GetBucketLocation'],get('SourceBucket','Arn')),
 allow(['ecr:GetAuthorizationToken'],'*'),
 allow(['ecr:BatchCheckLayerAvailability','ecr:InitiateLayerUpload','ecr:UploadLayerPart','ecr:CompleteLayerUpload','ecr:PutImage','ecr:BatchGetImage','ecr:GetDownloadUrlForLayer'],get('Repository','Arn'))])
buildspec={'version':0.2,'phases':{'pre_build':{'commands':['aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REPOSITORY_URI"']},'build':{'commands':['docker build -t "$REPOSITORY_URI:$IMAGE_TAG" .']},'post_build':{'commands':['docker push "$REPOSITORY_URI:$IMAGE_TAG"']}}}
r['Build']=resource('CodeBuild::Project',{'Name':'hishin-prod-build','ServiceRole':get('BuildRole','Arn'),'Artifacts':{'Type':'NO_ARTIFACTS'},'TimeoutInMinutes':30,'LogsConfig':{'CloudWatchLogs':{'Status':'ENABLED','GroupName':ref('BuildLogs')}},'Environment':{'Type':'LINUX_CONTAINER','ComputeType':'BUILD_GENERAL1_SMALL','Image':'aws/codebuild/standard:7.0','PrivilegedMode':True,'EnvironmentVariables':[{'Name':'REPOSITORY_URI','Value':get('Repository','RepositoryUri')},{'Name':'IMAGE_TAG','Value':'initial'}]},'Source':{'Type':'S3','Location':sub('${SourceBucket}/source.zip'),'BuildSpec':json.dumps(buildspec)}})
bootstrap={'AWSTemplateFormatVersion':'2010-09-09','Description':'HI-SHIN production image build','Resources':r,'Outputs':{'SourceBucket':{'Value':ref('SourceBucket')},'RepositoryUri':{'Value':get('Repository','RepositoryUri')},'BuildProject':{'Value':ref('Build')}}}
(P/'bootstrap.json').write_text(json.dumps(bootstrap,indent=2)+'\n')
r={}
r['AppLogs']=resource('Logs::LogGroup',{'LogGroupName':'/hishin/prod/app','RetentionInDays':7})
r['TranscribeBucket']=bucket()
r['Pool']=resource('Cognito::UserPool',{'UserPoolName':'hishin-prod','UserPoolTier':'LITE','UsernameAttributes':['email'],'AutoVerifiedAttributes':['email'],'UsernameConfiguration':{'CaseSensitive':False},'Policies':{'PasswordPolicy':{'MinimumLength':12,'RequireLowercase':True,'RequireUppercase':True,'RequireNumbers':True,'RequireSymbols':True}},'AccountRecoverySetting':{'RecoveryMechanisms':[{'Name':'verified_email','Priority':1}]},'Schema':[{'Name':'email','Required':True,'Mutable':True}],'AdminCreateUserConfig':{'AllowAdminCreateUserOnly':False}},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
r['PoolDomain']=resource('Cognito::UserPoolDomain',{'Domain':sub('hishin-${AWS::AccountId}-prod'),'UserPoolId':ref('Pool')})
r['PoolClient']=resource('Cognito::UserPoolClient',{'UserPoolId':ref('Pool'),'ClientName':'hishin-web','GenerateSecret':True,'AllowedOAuthFlowsUserPoolClient':True,'AllowedOAuthFlows':['code'],'AllowedOAuthScopes':['openid','email','profile'],'SupportedIdentityProviders':['COGNITO'],'CallbackURLs':['https://hishin.globalnavigator.app/oauth2/idpresponse'],'LogoutURLs':['https://hishin.globalnavigator.app/logged-out'],'PreventUserExistenceErrors':'ENABLED','EnableTokenRevocation':True,'RefreshTokenValidity':1})
r['Certificate']=resource('CertificateManager::Certificate',{'DomainName':'hishin.globalnavigator.app','ValidationMethod':'DNS','DomainValidationOptions':[{'DomainName':'hishin.globalnavigator.app','HostedZoneId':ref('HostedZoneId')}]})
r['AlbSG']=resource('EC2::SecurityGroup',{'GroupDescription':'Public HTTPS only','VpcId':ref('VpcId'),'SecurityGroupIngress':[{'IpProtocol':'tcp','FromPort':443,'ToPort':443,'CidrIp':'0.0.0.0/0'},{'IpProtocol':'tcp','FromPort':80,'ToPort':80,'CidrIp':'0.0.0.0/0'}]})
r['TaskSG']=resource('EC2::SecurityGroup',{'GroupDescription':'App only from ALB','VpcId':ref('VpcId'),'SecurityGroupIngress':[{'IpProtocol':'tcp','FromPort':3001,'ToPort':3001,'SourceSecurityGroupId':ref('AlbSG')}]})
r['EfsSG']=resource('EC2::SecurityGroup',{'GroupDescription':'NFS only from app','VpcId':ref('VpcId'),'SecurityGroupIngress':[{'IpProtocol':'tcp','FromPort':2049,'ToPort':2049,'SourceSecurityGroupId':ref('TaskSG')}]})
r['FileSystem']=resource('EFS::FileSystem',{'Encrypted':True,'PerformanceMode':'generalPurpose','ThroughputMode':'bursting','BackupPolicy':{'Status':'ENABLED'},'FileSystemPolicy':{'Version':'2012-10-17','Statement':[{'Effect':'Deny','Principal':'*','Action':'elasticfilesystem:*','Resource':'*','Condition':{'Bool':{'aws:SecureTransport':'false'}}}]}},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
r['AccessPoint']=resource('EFS::AccessPoint',{'FileSystemId':ref('FileSystem'),'PosixUser':{'Uid':'1000','Gid':'1000'},'RootDirectory':{'Path':'/hishin','CreationInfo':{'OwnerUid':'1000','OwnerGid':'1000','Permissions':'0750'}}})
for n in ('A','B'):r['Mount'+n]=resource('EFS::MountTarget',{'FileSystemId':ref('FileSystem'),'SubnetId':ref('Subnet'+n),'SecurityGroups':[ref('EfsSG')]})
r['Alb']=resource('ElasticLoadBalancingV2::LoadBalancer',{'Name':'hishin-prod','Scheme':'internet-facing','Type':'application','Subnets':[ref('SubnetA'),ref('SubnetB')],'SecurityGroups':[ref('AlbSG')],'LoadBalancerAttributes':[{'Key':'idle_timeout.timeout_seconds','Value':'300'},{'Key':'routing.http.drop_invalid_header_fields.enabled','Value':'true'}]})
r['Target']=resource('ElasticLoadBalancingV2::TargetGroup',{'VpcId':ref('VpcId'),'Protocol':'HTTP','Port':3001,'TargetType':'ip','HealthCheckPath':'/healthz','HealthCheckIntervalSeconds':30,'TargetGroupAttributes':[{'Key':'deregistration_delay.timeout_seconds','Value':'30'}]})
def auth(mode): return {'Type':'authenticate-cognito','Order':1,'AuthenticateCognitoConfig':{'UserPoolArn':get('Pool','Arn'),'UserPoolClientId':ref('PoolClient'),'UserPoolDomain':ref('PoolDomain'),'Scope':'openid email profile','SessionTimeout':3600,'OnUnauthenticatedRequest':mode}}
forward={'Type':'forward','Order':2,'TargetGroupArn':ref('Target')}
r['Https']=resource('ElasticLoadBalancingV2::Listener',{'LoadBalancerArn':ref('Alb'),'Port':443,'Protocol':'HTTPS','SslPolicy':'ELBSecurityPolicy-TLS13-1-2-2021-06','Certificates':[{'CertificateArn':ref('Certificate')}],'DefaultActions':[auth('authenticate'),forward]})
r['Http']=resource('ElasticLoadBalancingV2::Listener',{'LoadBalancerArn':ref('Alb'),'Port':80,'Protocol':'HTTP','DefaultActions':[{'Type':'redirect','RedirectConfig':{'Protocol':'HTTPS','Port':'443','StatusCode':'HTTP_301'}}]})
r['PublicPages']=resource('ElasticLoadBalancingV2::ListenerRule',{'ListenerArn':ref('Https'),'Priority':1,'Conditions':[{'Field':'path-pattern','Values':['/logged-out']}],'Actions':[{'Type':'forward','TargetGroupArn':ref('Target')}]})
r['ApiAuth']=resource('ElasticLoadBalancingV2::ListenerRule',{'ListenerArn':ref('Https'),'Priority':2,'Conditions':[{'Field':'path-pattern','Values':['/api/*']}],'Actions':[auth('deny'),forward]})
r['ExecutionRole']=role('ecs-tasks.amazonaws.com',[allow(['ecr:GetAuthorizationToken'],'*'),allow(['ecr:BatchGetImage','ecr:GetDownloadUrlForLayer','ecr:BatchCheckLayerAvailability'],sub('arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/hishin-prod')),allow(['logs:CreateLogStream','logs:PutLogEvents'],get('AppLogs','Arn'))])
r['TaskRole']=role('ecs-tasks.amazonaws.com',[
 allow(['elasticfilesystem:ClientMount','elasticfilesystem:ClientWrite'],get('FileSystem','Arn'),Condition={'StringEquals':{'elasticfilesystem:AccessPointArn':get('AccessPoint','Arn')}}),
 allow(['s3:PutObject','s3:GetObject'],sub('${TranscribeBucket.Arn}/hishin/*')),
 allow(['transcribe:StartTranscriptionJob','transcribe:GetTranscriptionJob'],sub('arn:aws:transcribe:${AWS::Region}:${AWS::AccountId}:transcription-job/*')),
 allow(['polly:SynthesizeSpeech','polly:DescribeVoices'],'*'),
 allow(['bedrock:InvokeModel','bedrock:InvokeModelWithResponseStream'],[sub('arn:aws:bedrock:*::foundation-model/anthropic.claude-sonnet-4-6'),sub('arn:aws:bedrock:*::foundation-model/anthropic.claude-haiku-4-5-20251001-v1:0'),sub('arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/us.anthropic.claude-sonnet-4-6'),sub('arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/us.anthropic.claude-haiku-4-5-20251001-v1:0')])])
r['Cluster']=resource('ECS::Cluster',{'ClusterName':'hishin-prod'})
env={'AUTH_MODE':'alb','APP_ORIGIN':'https://hishin.globalnavigator.app','AWS_REGION':ref('AWS::Region'),'ALB_ARN':ref('Alb'),'COGNITO_CLIENT_ID':ref('PoolClient'),'COGNITO_DOMAIN':sub('https://${PoolDomain}.auth.${AWS::Region}.amazoncognito.com'),'TRANSCRIBE_S3_BUCKET':ref('TranscribeBucket'),'BEDROCK_DIRECTOR_MODEL_ID':'us.anthropic.claude-sonnet-4-6','BEDROCK_CRITIC_MODEL_ID':'us.anthropic.claude-haiku-4-5-20251001-v1:0','MAX_REVISION_ROUNDS':'1','MEDIA_TIMEOUT_MS':'600000','MAX_UPLOAD_MB':'500'}
r['Task']=resource('ECS::TaskDefinition',{'Family':'hishin-prod','Cpu':'512','Memory':'2048','NetworkMode':'awsvpc','RequiresCompatibilities':['FARGATE'],'ExecutionRoleArn':get('ExecutionRole','Arn'),'TaskRoleArn':get('TaskRole','Arn'),'Volumes':[{'Name':'data','EFSVolumeConfiguration':{'FilesystemId':ref('FileSystem'),'TransitEncryption':'ENABLED','AuthorizationConfig':{'AccessPointId':ref('AccessPoint'),'IAM':'ENABLED'}}}],'ContainerDefinitions':[{'Name':'app','Image':ref('ImageUri'),'Essential':True,'StopTimeout':120,'PortMappings':[{'ContainerPort':3001}],'MountPoints':[{'SourceVolume':'data','ContainerPath':'/data'}],'Environment':[{'Name':k,'Value':v} for k,v in env.items()],'LogConfiguration':{'LogDriver':'awslogs','Options':{'awslogs-group':ref('AppLogs'),'awslogs-region':ref('AWS::Region'),'awslogs-stream-prefix':'app'}}}]})
r['Service']=resource('ECS::Service',{'ServiceName':'hishin-prod','Cluster':ref('Cluster'),'TaskDefinition':ref('Task'),'LaunchType':'FARGATE','PlatformVersion':'LATEST','DesiredCount':1,'HealthCheckGracePeriodSeconds':90,'DeploymentConfiguration':{'MinimumHealthyPercent':0,'MaximumPercent':100,'DeploymentCircuitBreaker':{'Enable':True,'Rollback':True}},'NetworkConfiguration':{'AwsvpcConfiguration':{'AssignPublicIp':'ENABLED','Subnets':[ref('SubnetA')],'SecurityGroups':[ref('TaskSG')]}},'LoadBalancers':[{'ContainerName':'app','ContainerPort':3001,'TargetGroupArn':ref('Target')}]},DependsOn=['Https','MountA','MountB'])
r['Dns']=resource('Route53::RecordSet',{'HostedZoneId':ref('HostedZoneId'),'Name':'hishin.globalnavigator.app','Type':'A','AliasTarget':{'DNSName':get('Alb','DNSName'),'HostedZoneId':get('Alb','CanonicalHostedZoneID')}})
prod={'AWSTemplateFormatVersion':'2010-09-09','Description':'HI-SHIN single-task production pilot with Cognito and persistent EFS','Parameters':{k:{'Type':'String'} for k in ['VpcId','SubnetA','SubnetB','HostedZoneId','ImageUri']},'Resources':r,'Outputs':{k:{'Value':v} for k,v in {'URL':'https://hishin.globalnavigator.app','PoolId':ref('Pool'),'ClientId':ref('PoolClient'),'AlbArn':ref('Alb'),'Cluster':ref('Cluster'),'TaskRoleArn':get('TaskRole','Arn'),'FileSystemId':ref('FileSystem')}.items()}}
(P/'production.json').write_text(json.dumps(prod,indent=2)+'\n')
